### ISSUE TITLE
how would I go about writing a filter to transform the response body

### ISSUE THREAD

**Issue by cameronbraid** [solo-io/proxy-runtime#20] opened 2020-06-03 14:35 UTC
I want to implement a filter that I can use in istio that allows me to generate custom html error pages

Changing the response headers is easy, how do I change the response body ?

**Comment by yuval-k** [comment] 2020-06-16 12:44
see #19

**Comment by Sodman** [comment] 2021-03-31 18:33
Closing as duplicate of #19

**Closed by Sodman** 2021-03-31 18:33 UTC
